defaults: &defaults
  adapter: postgresql
  encoding: utf8
  host: localhost
  prepared_statements: false
  pool: 20
  reaping_frequency: 30
  variables:
    lock_timeout: 3000
    idle_in_transaction_session_timeout: 45000

development:
  <<: *defaults
  database: houston_production_copy

test:
  <<: *defaults
  database: houston_test

# Just so we can precompile assets locally
production:
  <<: *defaults
  database: houston_production_copy
