development:
  adapter: postgresql
  encoding: utf8
  database: houston_production_copy
  host: localhost
  prepared_statements: false
  pool: 10
  reaping_frequency: 30

test:
  adapter: postgresql
  encoding: utf8
  database: houston_test
  host: localhost
  prepared_statements: false
  pool: 10
  reaping_frequency: 30

# Just so we can precompile assets locally
production:
  adapter: postgresql
  encoding: utf8
  database: houston_production_copy
  host: localhost
  prepared_statements: false
  pool: 10
  reaping_frequency: 30
